framework:
    cache:
        default_redis_provider: '%env(CACHE_URL)%'  # Utilise la variable d’environnement CACHE_URL
        pools:
            cache.auth:  # Pool de cache personnalisé pour auth (nom non réservé)
                adapter: cache.adapter.redis
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: breizhsport/auth